apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus-daemon
spec:
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.54.1
      tolerations:
        - key: "type"
          operator: "Equal"
          value: "Database"
          effect: "NoSchedule"
