apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-nginx
  labels:
    app: myapp
    tier: frontend
spec:
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      name: my-nginx-pod
      labels:
        app: myapp
        tier: frontend
    spec:
      containers:
        - name: my-nginx-container
          image: nginx
  replicas: 3